# Generated by Django 3.2.8 on 2021-10-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211029_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='sex_type',
            field=models.CharField(choices=[('male', 'Мужские'), ('female', 'Женские'), ('child', 'Детские'), ('all', 'Универсальные')], default='all', max_length=100, verbose_name='Пол'),
        ),
    ]
