# Generated by Django 3.2.8 on 2021-10-29 11:48

from django.db import migrations, models
import django.db.models.deletion
import mainapp.utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainapp', '0007_alter_shoes_sex_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.utils.uploading.upload_function),
        ),
        migrations.AddField(
            model_name='shoesbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.utils.uploading.upload_function),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=mainapp.utils.uploading.upload_function)),
                ('use_in_slider', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Галерея изображений',
                'verbose_name_plural': 'Галереи изображений',
            },
        ),
    ]
