# Generated by Django 3.2.8 on 2021-10-30 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20211030_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anonymous_user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания покупателя'),
        ),
    ]
