# Generated by Django 3.2.8 on 2021-10-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_cartproduct_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
