# Generated by Django 3.2.8 on 2021-11-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20211031_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesbrand',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='shoestype',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
