# Generated by Django 3.2.8 on 2021-11-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20211108_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesbrand',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='shoestype',
            name='slug',
            field=models.SlugField(),
        ),
    ]
